USE PROJECT 

SELECT * FROM BOD

--Analysis Questions:
--● Employee Performance:


--● Which department had the highest average profit margin among its
--products?

SELECT department from Bod  
group by department
order by avg(profit_margin) desc

SELECT SUM(REVENUE) FROM BOD

--● Which employee in the IT department had the highest performance score,
--and what was their role?

select top 5 department, employee_name ,employee_role from BOD
where department = 'IT'
order by employee_performance_score DESC

--● Product Sales & Customer Satisfaction:
--● Identify the product with the highest revenue generated in the HR
--department.



select   product_name from BOD
where department = 'HR'
group by product_name
order by sum(revenue) desc

--● What is the average customer feedback score for products in the Accessories category, and which product received the highest score?


select avg(customer_feedback_score)as avg_feedback from BOD
where product_name in (
    select product_name from BOD
    where category = 'Accessories'
     and customer_feedback_score = (
    select max(customer_feedback_score) as highest_feedback
    from BOD 
    where category = 'Accessories'
    )
    );



--● Supply Chain & Inventory Management:
--● Which supplier had the highest total inventory level across all
--departments?

select sum(inventory_level)as total_inventory,
department,supplier_name from BOD 
group by department,supplier_name
order by total_inventory desc

--● Which product in the Gadgets category had the lowest inventory level?

select * from BOD

select sum(inventory_level)as lowest_inventory,
product_name from BOD
where category = 'gadgets'
group by product_name


--● Employee Training & Sales:
--● How many employees in the Sales department have completed trainingprograms, and what percentage does this represent of the total employees
--in that department?

select * from BOD



select count(*) as training_completed,
department from BOD
where department = 'sales' and training_program_completed = '1'
group by department


select count(*) as training_completed,
department from BOD
where department = 'sales' 
group by department


SELECT 
  (SELECT COUNT(*) FROM BOD WHERE Department = 'Sales' AND training_program_completed = '1') * 100.0 /
  (SELECT COUNT(*) FROM BOD WHERE Department = 'Sales') AS CompletionRate;

--Product Sales Contribution:

--● What is the total number of units sold for all products in the Marketing
--department, and which product contributed the most to this total?

select * from BOD

select sum(units_sold) as total_units_sold,department,
product_name from BOD
where department = 'Marketing'
group by product_name,department

--Advanced SQL Questions
--● Write a query to rank employees in each department by their revenue
--generated using a window function.

select employee_id,employee_name,
        department,
        revenue,
        rank() over (partition by department order by revenue
        desc)as rank from BOD


--● Create a CTE to find the average salary of employees in each department
--and then select departments where the average salary is above $70,000.

select * from BOD

select avg(salary) as department_avg_salary,
employee_name,department
from BOD
where salary > 70000
group by employee_name,department






--● Create a view that shows only the product name, revenue, and profit
--margin for products in the Accessories category.

select * from BOD

create view Accessories_product_name as
select 
      product_name,
      category,
      revenue,
      profit_margin from BOD
      where category ='Accessories'

      select * from Accessories_product_name

--● Write a query to create a non-clustered index on the employee_name
--column to improve query performance.

CREATE NONCLUSTERED INDEX idx_employee_name 
ON BOD (employee_name);


--● Create a stored procedure that accepts a department name as a
--parameter and returns the total revenue generated by that department.

select * from BOD

create procedure getdepartmentrevenue
@department_name varchar(50)
as 
begin 
  select sum(revenue),department
  from BOD
  where department = @department_name
  group by department
  end

  execute  getdepartmentrevenue 'HR'


--● Write a trigger that logs changes to the revenue column in a separate table
--whenever an update occurs.




--● Create a scalar UDF that calculates the profit from a given product's revenue and profit margin.

select * from BOD

create function dbo.calculates_profit(
 @revenue decimal(10,2),
 @profitmargin decimal(5,2)
 )
 returns decimal(10,2)
 as 
 begin
     return
   
       @revenue * (@profitmargin / 100)
     end
   

 select 
   product_name,
   revenue,
   profit_margin,
   dbo.calculates_profit(revenue, profit_margin) as profit
   from BOD



    
--● Provide a query to create a clustered index on the company_id column.
     
     select * from BOD

     drop index idx_company_id on BOD

   CREATE CLUSTERED INDEX idx_company_id
ON BOD (company_id);