USE PROJECT 

SELECT * FROM BOD

--Analysis Questions:
--● Employee Performance:


--● Which department had the highest average profit margin among its
--products?


SELECT department, AVG(profit_margin) AS avg_margin
FROM BOD
GROUP BY department
ORDER BY avg_margin DESC;

--total revenue
SELECT SUM(REVENUE) FROM BOD

--● Which employee in the IT department had the highest performance score,
--and what was their role?

select top 5 department, employee_name ,employee_role from BOD
where department = 'IT'
order by employee_performance_score DESC

--● Product Sales & Customer Satisfaction:
--● Identify the product with the highest revenue generated in the HR
--department.




SELECT product_name, SUM(revenue) AS total_revenue
FROM BOD
WHERE department = 'HR'
GROUP BY product_name
ORDER BY total_revenue DESC

--● What is the average customer feedback score for products in the Accessories category, and which product received the highest score?


    SELECT top 5
    product_name,
    customer_feedback_score,
    AVG(customer_feedback_score) OVER () AS avg_feedback
FROM BOD
WHERE category = 'Accessories'
  AND customer_feedback_score = (
    SELECT MAX(customer_feedback_score)
    FROM BOD
    WHERE category = 'Accessories'
  );
  
  SELECT  
  product_name,
  customer_feedback_score,
  AVG(customer_feedback_score) OVER () AS avg_feedback
FROM BOD
WHERE category = 'Accessories';



--● Supply Chain & Inventory Management:
--● Which supplier had the highest total inventory level across all
--departments?

select top 1 supplier_name ,sum(inventory_level)as total_inventory
 from BOD 
group by supplier_name
order by total_inventory desc



--● Which product in the Gadgets category had the lowest inventory level?

select * from BOD



SELECT 
    product_name,
    SUM(inventory_level) AS lowest_inventory
FROM BOD
WHERE category = 'gadgets'
GROUP BY product_name
ORDER BY lowest_inventory ASC


--● Employee Training & Sales:
--● How many employees in the Sales department have completed trainingprograms, and what percentage does this represent of the total employees
--in that department?

select * from BOD



select count(*) as training_completed,
department from BOD
where department = 'sales' and training_program_completed = '1'
group by department


select count(*) as joined_training ,
department from BOD
where department = 'sales' 
group by department


SELECT 
  (SELECT COUNT(*) FROM BOD WHERE Department = 'Sales' AND training_program_completed = '1') * 100.0 /
  (SELECT COUNT(*) FROM BOD WHERE Department = 'Sales') AS CompletionRate;

--Product Sales Contribution:

--● What is the total number of units sold for all products in the Marketing
--department, and which product contributed the most to this total?

select * from BOD

select sum(units_sold) as total_units_sold
from BOD
where department = 'Marketing'
-- Top contributing product:
SELECT  product_name, SUM(units_sold) AS units
FROM BOD
WHERE department = 'Marketing'
GROUP BY product_name
ORDER BY units DESC

--Advanced SQL Questions
--● Write a query to rank employees in each department by their revenue
--generated using a window function.

select employee_id,employee_name,
        department,
        revenue,
        rank() over (partition by department order by revenue
        desc)as rank from BOD


--● Create a CTE to find the average salary of employees in each department
--and then select departments where the average salary is above $70,000.

select * from BOD


WITH DeptAvgSalary AS (
  SELECT department, AVG(salary) AS avg_salary
  FROM BOD
  GROUP BY department
)
SELECT *
FROM DeptAvgSalary
WHERE avg_salary > 70000;




--● Create a view that shows only the product name, revenue, and profit
--margin for products in the Accessories category.

select * from BOD

create view Accessories_product_name as
select 
      product_name,
      category,
      revenue,
      profit_margin from BOD
      where category ='Accessories'

      select * from Accessories_product_name

--● Write a query to create a non-clustered index on the employee_name
--column to improve query performance.

CREATE NONCLUSTERED INDEX idx_employee_name 
ON BOD (employee_name);


--● Create a stored procedure that accepts a department name as a
--parameter and returns the total revenue generated by that department.

select * from BOD
create procedure getdepartmentrevenue
@department_name varchar(50)
as 
begin 
  select sum(revenue)as department_revenue,department
  from BOD
  where department = @department_name
  group by department
  end

  execute  getdepartmentrevenue 'HR'


--● Write a trigger that logs changes to the revenue column in a separate table
--whenever an update occurs.

CREATE TRIGGER trg_log_revenue_change
ON BOD
AFTER UPDATE
AS
BEGIN
  IF UPDATE(revenue)
  BEGIN
    INSERT INTO RevenueLog (product_name, old_revenue, new_revenue, change_date)
    SELECT d.product_name, d.revenue, i.revenue, GETDATE()
    FROM deleted d
    JOIN inserted i ON d.product_id = i.product_id;
  END
END;


--● Create a scalar UDF that calculates the profit from a given product's revenue and profit margin.

select * from BOD

create function dbo.calculates_profit(
 @revenue decimal(10,2),
 @profitmargin decimal(5,2)
 )
 returns decimal(10,2)
 as 
 begin
     return
   
       @revenue * (@profitmargin / 100)
     end
   

 select 
   product_name,
   revenue,
   profit_margin,
   dbo.calculates_profit(revenue, profit_margin) as profit
   from BOD



    
--● Provide a query to create a clustered index on the company_id column.
     
     select * from BOD


   CREATE CLUSTERED INDEX idx_company_id
ON BOD (company_id);