                                          --Case study 1

--1. Display the number of states present in the LocationTable.

select  count(distinct state) from location

--2. How many products are of regular type?

select * from product

select count(type) as count from product where type = 'regular'

--3. How much spending has been done on marketing of product ID 1?
select * from fact

select sum(MARKETING) AS TOTAL_SEPENDNG FROM FACT WHERE PRODUCTID = 1


--4. What is the minimum sales of a product?
SELECT min(sales) as min_sales from fact group by productid


SELECT productid, min(sales) as min_sales from fact group by productid



--5. Display the max Cost of Good Sold (COGS). 
select * from fact

select max(cogs)as max_cost from fact

--6. Display the details of the product where product type is coffee.

select* from product where product_type ='coffee'



--7. Display the details where total expenses are greater than 40. 

select * from fact where total_expenses>40


--8. What is the average sales in area code 719?
     select avg(sales) as avg_sales from fact where Area_Code=719

--9. Find out the total profit generated by Colorado state.
    
    select state,sum(profit) as total_profit from fact 
    inner join location 
    on fact.area_code=location.area_code
    where state='colorado'
    group by state


--10. Display the average inventory for each product ID.
 select productid, avg(inventory) as avg_inventory from fact 
 group by productid


--11. Display state in a sequential order in a Location Table.

   select state from location group by state order by state

--12. Display the average budget of the Product where the average budget margin should be greater than 100. 
    select product,avg(budget_margin) as avg_bm from fact 
    inner join product
    on fact.productid=product.productid
    group by product
    having avg(budget_margin)>100


--13. What is the total sales done on date 2010-01-01?

     select date,sum( sales)as total_sales from fact where date='2010-01-01'
     group by date


--14. Display the average total expense of each product ID on an individual date.
 select  productid,date,avg(total_expenses ) as avg_total_expenses from fact 
 group by productid,date
 order by productid,date


--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.

  select date,fact.productid,product_type,product,sales,profit,state,fact.area_code from fact
  join product
  on fact.productid=product.productid
  join location
  on fact.area_code=location.area_code
  

--16. Display the rank without any gap to show the sales wise rank.


select*, dense_rank()over (order by sales desc) as sales_rank from fact



--17. Find the state wise profit and sales.

    select location.state,sum(profit)as total_profit,sum(sales) as total_sales   from fact
    join location
    on fact.area_code=location.area_code
    group by state



--18. Find the state wise profit and sales along with the productname.

   select location.state,product.product,sum(profit)as total_profit,sum(sales)as total_sales from fact
   join product
   on fact.productid=product.productid
   join location
   on fact.area_code=location.area_code
   group by state,product

   select* from product

--19. If there is an increase in sales of 5%, calculate the increasedsales.

   select date,productid,sales,sales*1.05 as incresed_sales from fact




--20. Find the maximum profit along with the product ID and producttype.

select p.productid,p.product_type, max(profit)as max_profit from fact
join product as p
on fact.productid=p.productid
group by p.productid,p.product_type

--21. Create a stored procedure to fetch the result according to the product typefrom Product Table.

    create procedure usp_product_type
    (
    @product_type varchar(50)
    )
    as
    select * from product where product_type=@product_type

    execute usp_product_type 'coffee'

--22. Write a query by creating a condition in which if the total expenses is lessthan60 then it is a profit or else loss.
    
    select *,
    case
    when total_expenses<60 then 'profit'
    else 'loss'
    end as profit_and_loss
    from
    fact

--23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order. 

select datepart(week,date) as week ,date,productid,sum(sales) as total_sales
from fact group by rollup(datepart(week,date),date,productid)


--24. Apply union and intersection operator on the tables which consist of attribute area code.

     SELECT AREA_CODE  FROM FACT 
     UNION 
     SELECT AREA_CODE FROM LOCATION
  

       SELECT AREA_CODE  FROM FACT 
     INTERSECT
     SELECT AREA_CODE FROM LOCATION
  
--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.

    create function getproducttype
    (
    @product_type varchar(50)
    )
    returns table
    as
    return
    select * from product where Product_Type=@product_type

    select * from getproducttype('coffee')
    

--26. Change the product type from coffee to tea where product IDis 1 and undo it. 
    
    update product set 
    Product_Type='tea'
    where productid=1

     update product set 
    Product_Type='coffee'
    where productid=1



--27. Display the date, product ID and sales where total expenses are between 100 to 200.

select date,productid,sales
from fact
where total_expenses  between 100 and 200


--28. Delete the records in the Product Table for regular type. 
delete from product
where Type='regular'


select * from product



--29. Display the ASCII value of the fifth character from the columnProduct.

select ASCII(substring(product,5,1)) as fifthcharacterASCII
from product 



